2024-06-07 14:04:04,018 - __main__ - ERROR - Database connection failed: Textual SQL expression 'SELECT 1' should be explicitly declared as text('SELECT 1')
2024-06-07 14:10:18,604 - __main__ - ERROR - Database connection failed: Textual SQL expression 'SELECT 1' should be explicitly declared as text('SELECT 1')
2024-06-07 14:10:21,785 - __main__ - ERROR - Database connection failed: Textual SQL expression 'SELECT 1' should be explicitly declared as text('SELECT 1')
2024-06-07 18:58:20,770 - __main__ - ERROR - Database initialization failed: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.
2024-06-07 19:31:28,629 - __main__ - ERROR - Database initialization failed: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.
2024-06-07 19:34:13,634 - __main__ - ERROR - Database initialization failed: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.
2024-06-07 19:35:18,607 - __main__ - ERROR - Database initialization failed: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.
2024-11-09 16:10:03,810 - __main__ - ERROR - Database initialization failed: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s]
[parameters: {'table_name': 'producaointelectual', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
